In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
from datetime import datetime
import os, time

from scipy import stats
from sklearn.linear_model import LinearRegression
from typing import Optional
from fastf1.core import Session
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.stattools import grangercausalitytests
!pip install fastf1
import fastf1 as ff1
from fastf1 import plotting



os.chdir('/Users/jackson/Documents/ECON570')

Requirement already satisfied: fastf1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (3.6.1)
Requirement already satisfied: matplotlib<4.0.0,>=3.5.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (3.8.4)
Requirement already satisfied: numpy<3.0.0,>=1.23.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=1.4.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (2.2.2)
Requirement already satisfied: python-dateutil in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (2.9.0.post0)
Requirement already satisfied: rapidfuzz in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (3.14.1)
Requirement already satisfied: requests-cache>=1.0.0 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (1.2.1)
Requirement already satisfied: requests>=2.28.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.8.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (1.15.3)
Requirement already satisfied: timple>=0.1.6 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (0.1.8)
Requirement already satisfied: websockets<14,>=10.3 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (13.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (25.0)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from pandas<3.0.0,>=1.4.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from pandas<3.0.0,>=1.4.1->fastf1) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests>=2.28.1->fastf1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests>=2.28.1->fastf1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests>=2.28.1->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests>=2.28.1->fastf1) (2025.8.3)
Requirement already satisfied: attrs>=21.2 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (4.3.7)
Requirement already satisfied: url-normalize>=1.4 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (2.2.1)
Requirement already satisfied: exceptiongroup>=1.1.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (1.2.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (4.15.0)

In [2]:
import fastf1
fastf1.Cache.enable_cache("F1/f1_cache")
fastf1.get_event_schedule(2021)

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 2021,2021-03-14,Pre-Season Test,testing,Practice 1,2021-03-12 10:00:00+03:00,2021-03-12 07:00:00,...,Practice 3,2021-03-14 10:00:00+03:00,2021-03-14 07:00:00,None,NaT,NaT,None,NaT,NaT,False
1,1,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2021,2021-03-28,Bahrain Grand Prix,conventional,Practice 1,2021-03-26 14:30:00+03:00,2021-03-26 11:30:00,...,Practice 3,2021-03-27 15:00:00+03:00,2021-03-27 12:00:00,Qualifying,2021-03-27 18:00:00+03:00,2021-03-27 15:00:00,Race,2021-03-28 18:00:00+03:00,2021-03-28 15:00:00,True
2,2,Italy,Imola,FORMULA 1 PIRELLI GRAN PREMIO DEL MADE IN ITAL...,2021-04-18,Emilia Romagna Grand Prix,conventional,Practice 1,2021-04-16 11:00:00+02:00,2021-04-16 09:00:00,...,Practice 3,2021-04-17 11:00:00+02:00,2021-04-17 09:00:00,Qualifying,2021-04-17 14:00:00+02:00,2021-04-17 12:00:00,Race,2021-04-18 15:00:00+02:00,2021-04-18 13:00:00,True
3,3,Portugal,Portimão,FORMULA 1 HEINEKEN GRANDE PRÉMIO DE PORTUGAL 2021,2021-05-02,Portuguese Grand Prix,conventional,Practice 1,2021-04-30 11:30:00+01:00,2021-04-30 10:30:00,...,Practice 3,2021-05-01 12:00:00+01:00,2021-05-01 11:00:00,Qualifying,2021-05-01 15:00:00+01:00,2021-05-01 14:00:00,Race,2021-05-02 15:00:00+01:00,2021-05-02 14:00:00,True
4,4,Spain,Barcelona,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2021,2021-05-09,Spanish Grand Prix,conventional,Practice 1,2021-05-07 11:30:00+02:00,2021-05-07 09:30:00,...,Practice 3,2021-05-08 12:00:00+02:00,2021-05-08 10:00:00,Qualifying,2021-05-08 15:00:00+02:00,2021-05-08 13:00:00,Race,2021-05-09 15:00:00+02:00,2021-05-09 13:00:00,True
5,5,Monaco,Monte Carlo,FORMULA 1 GRAND PRIX DE MONACO 2021,2021-05-23,Monaco Grand Prix,conventional,Practice 1,2021-05-20 11:30:00+02:00,2021-05-20 09:30:00,...,Practice 3,2021-05-22 12:00:00+02:00,2021-05-22 10:00:00,Qualifying,2021-05-22 15:00:00+02:00,2021-05-22 13:00:00,Race,2021-05-23 15:00:00+02:00,2021-05-23 13:00:00,True
6,6,Azerbaijan,Baku,FORMULA 1 AZERBAIJAN GRAND PRIX 2021,2021-06-06,Azerbaijan Grand Prix,conventional,Practice 1,2021-06-04 12:30:00+04:00,2021-06-04 08:30:00,...,Practice 3,2021-06-05 13:00:00+04:00,2021-06-05 09:00:00,Qualifying,2021-06-05 16:00:00+04:00,2021-06-05 12:00:00,Race,2021-06-06 16:00:00+04:00,2021-06-06 12:00:00,True
7,7,France,Le Castellet,FORMULA 1 EMIRATES GRAND PRIX DE FRANCE 2021,2021-06-20,French Grand Prix,conventional,Practice 1,2021-06-18 11:30:00+02:00,2021-06-18 09:30:00,...,Practice 3,2021-06-19 12:00:00+02:00,2021-06-19 10:00:00,Qualifying,2021-06-19 15:00:00+02:00,2021-06-19 13:00:00,Race,2021-06-20 15:00:00+02:00,2021-06-20 13:00:00,True
8,8,Austria,Spielberg,FORMULA 1 BWT GROSSER PREIS DER STEIERMARK 2021,2021-06-27,Styrian Grand Prix,conventional,Practice 1,2021-06-25 11:30:00+02:00,2021-06-25 09:30:00,...,Practice 3,2021-06-26 12:00:00+02:00,2021-06-26 10:00:00,Qualifying,2021-06-26 15:00:00+02:00,2021-06-26 13:00:00,Race,2021-06-27 15:00:00+02:00,2021-06-27 13:00:00,True
9,9,Austria,Spielberg,FORMULA 1 BWT GROSSER PREIS VON ÖSTERREICH 2021,2021-07-04,Austrian Grand Prix,conventional,Practice 1,2021-07-02 11:30:00+02:00,2021-07-02 09:30:00,...,Practice 3,2021-07-03 12:00:00+02:00,2021-07-03 10:00:00,Qualifying,2021-07-03 15:00:00+02:00,2021-07-03 13:00:00,Race,2021-07-04 15:00:00+02:00,2021-07-04 13:00:00,True
10,10,Great Britain,Silverstone,FORMULA 1 PIRELLI BRITISH GRAND PRIX 2021,2021-07-18,British Grand Prix,sprint,Practice 1,2021-07-16 14:30:00+01:00,2021-07-16 13:30:00,...,Practice 2,2021-07-17 12:00:00+01:00,2021-07-17 11:00:00,Sprint,2021-07-17 16:30:00+01:00,2021-07-17 15:30:00,Race,2021-07-18 15:00:00+01:00,2021-07-18 14:00:00,True
11,11,Hungary,Budapest,FORMULA 1 ROLEX MAGYAR NAGYDÍJ 2021,2021-08-01,Hungarian Grand Prix,conventional,Practice 1,2021-07-30 11:30:00+02:00,2021-07-30 09:30:00,...,Practice 3,2021-07-31 12:00:00+02:00,2021-07-31 10:00:00,Qualifying,2021-07-31 15:00:00+02:00,2021-07-31 13:00:00,Race,2021-08-01 15:00:00+02:00,2021-08-01 13:00:00,True
12,12,Belgium,Spa-Francorchamps,FORMULA 1 ROLEX BELGIAN GRAND PRIX 2021,2021-08-29,Belgian Grand Prix,conventional,Practice 1,2021-08-27 11:30:00+02:00,2021-08-27 09:30:00,...,Practice 3,2021-08-28 12:00:00+02:00,2021-08-28 10:00:00,Qualifying,2021-08-28 15:00:00+02:00,2021-08-28 13:00:00,Race,2021-08-29 15:00:00+02:00,2021-08-29 13:00:00,True
13,13,Netherlands,Zandvoort,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2021,2021-09-05,Dutch Grand Prix,conventional,Practice 1,2021-09-03 11:30:00+02:00,2021-09-03 09:30:00,...,Practice 3,2021-09-04 12:00:00+02:00,2021-09-04 10:00:00,Qualifying,2021-09-04 15:00:00+02:00,2021-09-04 13:00:00,Race,2021-09-05 15:00:00+02:00,2021-09-05 13:00:00,True
14,14,Italy,Monza,FORMULA 1 HEINEKEN GRAN PREMIO D’ITALIA 2021,2021-09-12,Italian Grand Prix,sprint,Practice 1,2021-09-10 14:30:00+02:00,2021-09-10 12:30:00,...,Practice 2,2021-09-11 12:00:00+02:00,2021-09-11 10:00:00,Sprint,2021-09-11 16:30:00+02:00,2021-09-11 14:30:00,Race,2021-09-12 15:00:00+02:00,2021-09-12 13:00:00,True
15,15,Russia,Sochi,FORMULA 1 VTB RUSSIAN GRAND PRIX 2021,2021-09-26,Russian Grand Prix,conventional,Practice 1,2021-09-24 11:30:00+03:00,2021-09-24 08:30:00,...,Practice 3,2021-09-25 12:00:00+03:00,2021-09-25 09:00:00,Qualifying,2021-09-25 15:00:00+03:00,2021-09-25 12:00:00,Race,2021-09-26 15:00:00+03:00,2021-09-26 12:00:00,True
16,16,Turkey,Istanbul,FORMULA 1 ROLEX TURKISH GRAND PRIX 2021,2021-10-10,Turkish Grand Prix,conventional,Practice 1,2021-10-08 11:30:00+03:00,2021-10-08 08:30:00,...,Practice 3,2021-10-09 12:00:00+03:00,2021-10-09 09:00:00,Qualifying,2021-10-09 15:00:00+03:00,2021-10-09 12:00:00,Race,2021-10-10 15:00:00+03:00,2021-10-10 12:00:00,True
17,17,United States,Austin,FORMULA 1 ARAMCO UNITED STATES GRAND PRIX 2021,2021-10-24,United States Grand Prix,conventional,Practice 1,2021-10-22 11:30:00-05:00,2021-10-22 16:30:00,...,Practice 3,2021-10-23 13:00:00-05:00,2021-10-23 18:00:00,Qualifying,2021-10-23 16:00:00-05:00,2021-10-23 21:00:00,Race,2021-10-24 14:00:00-05:00,2021-10-24 19:00:00,True
18,18,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2021,2021-11-07,Mexico City Grand Prix,conventional,Practice 1,2021-11-05 11:30:00-06:00,2021-11-05 17:30:00,...,Practice 3,2021-11-06 11:00:00-06:00,2021-11-06 17:00:00,Qualifying,2021-11-06 14:00:00-06:00,2021-11-06 20:00:00,Race,2021-11-07 13:00:00-06:00,2021-11-07 19:00:00,True
19,19,Brazil,São Paulo,FORMULA 1 HEINEKEN GRANDE PRÊMIO DE SÃO PAULO ...,2021-11-14,São Paulo Grand Prix,sprint,Practice 1,2021-11-12 12:30:00-03:00,2021-11-12 15:30:00,...,Practice 2,2021-11-13 12:00:00-03:00,2021-11-13 15:00:00,Sprint,2021-11-13 16:30:00-03:00,2021-11-13 19:30:00,Race,2021-11-14 14:00:00-03:00,2021-11-14 17:00:00,True
20,20,Qatar,Lusail,FORMULA 1 OOREDOO QATAR GRAND PRIX 2021,2021-11-21,Qatar Grand Prix,conventional,Practice 1,2021-11-19 13:30:00+03:00,2021-11-19 10:30:00,...,Practice 3,2021-11-20 14:00:00+03:00,2021-11-20 11:00:00,Qualifying,2021-11-20 17:00:00+03:00,2021-11-20 14:00:00,Race,2021-11-21 17:00:00+03:00,2021-11-21 14:00:00,True
21,21,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2021,2021-12-05,Saudi Arabian Grand Prix,conventional,Practice 1,2021-12-03 16:30:00+03:00,2021-12-03 13:30:00,...,Practice 3,2021-12-04 17:00:00+03:00,2021-12-04 14:00:00,Qualifying,2021-12-04 20:00:00+03:00,2021-12-04 17:00:00,Race,2021-12-05 20:30:00+03:00,2021-12-05 17:30:00,True
22,22,Abu Dhabi,Yas Island,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2021-12-12,Abu Dhabi Grand Prix,conventional,Practice 1,2021-12-10 13:30:00+04:00,2021-12-10 09:30:00,...,Practice 3,2021-12-11 14:00:00+04:00,2021-12-11 10:00:00,Qualifying,2021-12-11 17:00:00+04:00,2021-12-11 13:00:00,Race,2021-12-12 17:00:00+04:00,2021-12-12 13:00:00,True

In [ ]:
ff1.Cache.enable_cache("F1/f1_cache") #rel path

years = range(2014, 2024)  # example window

records = []

for year in years:
    session = ff1.get_session(year, "Bahrain Grand Prix", "R")
    session.load()

    for drv in session.drivers:
        d = session.get_driver(drv)
        records.append({
            "year": year,
            "team_f1": d["TeamName"],     # e.g. 'Mercedes', 'McLaren'
            "driver_code": d["Abbreviation"],  # 'HAM', 'NOR', etc.
            "driver_name": d["FullName"]
        })

driver_year_df = pd.DataFrame(records)

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO 	Finished loading data for 22 drivers: ['44', '6', '11', '3', '27', '1', '19', '77', '14', '7', '26', '8', '4', '13', '10', '17', '22', '20', '21', '9', '25', '99']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO 	Finished loading data for 20 drivers: ['44', '7', '6', '77', '5', '3', '8', '11', '26', '19', '14', '12', '27', '9', '13', '28', '98', '33', '55', '22']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO 	Finished loading data for 22 drivers: ['6', '7', '44', '3', '8', '33', '26', '19', '77', '47', '20', '9', '94', '12', '27', '11', '88', '55', '21', '22', '5', '30']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '77', '7', '3', '19', '11', '8', '27', '31', '94', '26', '30', '14', '9', '55', '18', '33', '20', '2']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!
core        WARNING 	Failed to determine `Session.t0_date`!
logger      WARNING 	Failed to load telemetry data!
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '77', '44', '10', '20', '27', '14', '2', '9', '31', '55', '16', '8', '18', '35', '11', '28', '7', '33', '3']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.070000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '5', '4', '7', '10', '23', '11', '99', '26', '20', '18', '63', '88', '27', '3', '55', '8']
events      WARNING 	Correcting user input 'Bahrain Grand Prix' to 'Bahrain Grand Prix'
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '23', '4', '55', '10', '3', '77', '31', '16', '26', '63', '5', '6', '7', '99', '20', '11', '18', '8']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.067000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '4', '11', '16', '3', '55', '22', '18', '7', '99', '31', '63', '5', '47', '10', '6', '14', '9']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 16 completed the race distance 00:00.050000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '44', '63', '20', '77', '31', '22', '14', '24', '47', '18', '23', '3', '4', '6', '27', '11', '1', '10']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

In [4]:
team_lineups = (
    driver_year_df
    .groupby(["team_f1", "year"])["driver_code"]
    .apply(lambda x: tuple(sorted(set(x))))
    .reset_index(name="drivers")
)

In [5]:
team_lineups = team_lineups.sort_values(["team_f1", "year"])

team_lineups["drivers_prev"] = (
    team_lineups
    .groupby("team_f1")["drivers"]
    .shift(1)
)

team_lineups["driver_change"] = (
    (team_lineups["drivers"] != team_lineups["drivers_prev"])
    .astype(int)
)

In [6]:
name_map = {
    "Mercedes": "Mercedes",       # or 'Mercedes-Benz Grand Prix Ltd'
    "McLaren": "McLaren",
    "Ferrari": "Ferrari",
    "Red Bull Racing": "Red Bull",  # etc.
    # add others
}

team_lineups["team_clean_name"] = team_lineups["team_f1"].map(name_map)

In [ ]:
profits_df = pd.read_csv("F1/f1_financial_data.csv")
profits_df.head()

profits_df = pd.read_csv("F1/f1_financial_data.csv")

profits_df = profits_df.rename(columns={
    "Team": "team_clean_name",
    "Year": "year",
    "Operating Profit (£m)": "profit"   #main profit metric
})

profits_df.head()
panel = team_lineups.merge(
    profits_df,
    on=["team_clean_name", "year"],
    how="inner"
)

# Profit change vs previous season within a team
panel = panel.sort_values(["team_clean_name", "year"])

panel["profit_prev"] = (
    panel
    .groupby("team_clean_name")["profit"]
    .shift(1)
)

panel["profit_change"] = panel["profit"] - panel["profit_prev"]

panel.head()

,team_f1,year,drivers,drivers_prev,driver_change,team_clean_name,Legal Entity,Country,Revenue (£m),profit,Net Income (£m),Prize Money (£m),Employees,Source,profit_prev,profit_change
0,Ferrari,2019,"(LEC, VET)","(RAI, VET)",1,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,380,13,10,180,950,Ferrari Annual Report,NaN,NaN
1,Ferrari,2020,"(LEC, VET)","(LEC, VET)",0,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,350,9,7,165,930,NaN,13.0,-4.0
2,Ferrari,2021,"(LEC, SAI)","(LEC, VET)",1,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,365,12,9,170,940,NaN,9.0,3.0
3,Ferrari,2022,"(LEC, SAI)","(LEC, SAI)",0,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,392,15,12,178,960,NaN,12.0,3.0
4,Ferrari,2023,"(LEC, SAI)","(LEC, SAI)",0,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,405,17,13,180,970,NaN,15.0,2.0

In [ ]:

name_map = {
    # Sauber lineage
    "Sauber": "Alfa Romeo",
    "Alfa Romeo Racing": "Alfa Romeo",
    "Alfa Romeo": "Alfa Romeo",

    # Toro Rosso / AlphaTauri lineage
    "Toro Rosso": "AlphaTauri",
    "AlphaTauri": "AlphaTauri",

    # Renault / Lotus / Alpine lineage
    "Renault": "Alpine",
    "Lotus F1": "Alpine",
    "Alpine": "Alpine",

    # Force India / Racing Point / Aston Martin lineage
    "Force India": "Aston Martin",
    "Racing Point": "Aston Martin",
    "Aston Martin": "Aston Martin",

    # Red Bull lineage
    "Red Bull": "Red Bull Racing",
    "Red Bull Racing": "Red Bull Racing",

    # Marussia / Manor
    "Marussia": "Manor Marussia",
    "Manor Marussia": "Manor Marussia",

    # Stable names
    "Ferrari": "Ferrari",
    "McLaren": "McLaren",
    "Mercedes": "Mercedes",
    "Haas F1 Team": "Haas F1 Team",
    "Caterham": "Caterham",}

team_lineups["team_clean_name"] = (
    team_lineups["team_f1"].map(name_map).fillna(team_lineups["team_f1"])
)

team_lineups[["team_f1", "team_clean_name"]].drop_duplicates().sort_values("team_f1")



team_lineups["team_clean_name"] = team_lineups["team_f1"].map(name_map)

In [19]:
print(team_lineups.columns)
print(team_lineups[["team_f1", "team_clean_name"]].drop_duplicates().head(20)) # assimilate teams to make names the same (teams change title sponsors and hence team names)

Index(['team_f1', 'year', 'drivers', 'drivers_prev', 'driver_change',
       'team_clean_name'],
      dtype='object')
              team_f1  team_clean_name
0          Alfa Romeo       Alfa Romeo
2   Alfa Romeo Racing       Alfa Romeo
5          AlphaTauri       AlphaTauri
9              Alpine           Alpine
12       Aston Martin     Aston Martin
15           Caterham         Caterham
16            Ferrari          Ferrari
26        Force India     Aston Martin
31       Haas F1 Team     Haas F1 Team
39           Lotus F1           Alpine
41     Manor Marussia   Manor Marussia
43           Marussia   Manor Marussia
44            McLaren          McLaren
54           Mercedes         Mercedes
64       Racing Point     Aston Martin
66           Red Bull  Red Bull Racing
70    Red Bull Racing  Red Bull Racing
76            Renault           Alpine
81             Sauber       Alfa Romeo
86         Toro Rosso       AlphaTauri

In [10]:
    panel = team_lineups.merge(
    profits_df[["team_clean_name", "year", "profit", "Revenue (£m)", "Net Income (£m)"]],
    on=["team_clean_name", "year"],
    how="inner"
)

Show year(s) that teams had driver changes, and their profits on each year

In [11]:
panel[["team_clean_name", "year", "drivers", "profit"]]

    team_clean_name  year     drivers  profit
0        AlphaTauri  2020  (GAS, KVY)       1
1        AlphaTauri  2021  (GAS, TSU)       2
2        AlphaTauri  2022  (GAS, TSU)       3
3        AlphaTauri  2023  (DEV, TSU)       4
4            Alpine  2021  (ALO, OCO)       1
5            Alpine  2022  (ALO, OCO)       3
6            Alpine  2023  (GAS, OCO)       4
7      Aston Martin  2021  (STR, VET)       2
8      Aston Martin  2022  (HUL, STR)       5
9      Aston Martin  2023  (ALO, STR)       8
10          Ferrari  2019  (LEC, VET)      13
11          Ferrari  2020  (LEC, VET)       9
12          Ferrari  2021  (LEC, SAI)      12
13          Ferrari  2022  (LEC, SAI)      15
14          Ferrari  2023  (LEC, SAI)      17
15          McLaren  2019  (NOR, SAI)      -2
16          McLaren  2020  (NOR, SAI)      -5
17          McLaren  2021  (NOR, RIC)       3
18          McLaren  2022  (NOR, RIC)       5
19          McLaren  2023  (NOR, PIA)       8
20         Mercedes  2019  (BOT, HAM)      18
21         Mercedes  2020  (BOT, HAM)      16
22         Mercedes  2021  (BOT, HAM)      22
23         Mercedes  2022  (HAM, RUS)      19
24         Mercedes  2023  (HAM, RUS)      15
25     Aston Martin  2019  (PER, STR)      -6
26     Aston Martin  2020  (PER, STR)      -4
27  Red Bull Racing  2019  (GAS, VER)       4
28  Red Bull Racing  2020  (ALB, VER)       2
29  Red Bull Racing  2021  (PER, VER)       5
30  Red Bull Racing  2022  (PER, VER)       6
31  Red Bull Racing  2023  (PER, VER)       7
32           Alpine  2019  (HUL, RIC)      -2
33           Alpine  2020  (OCO, RIC)      -3
34       AlphaTauri  2019  (ALB, KVY)      -3

In [ ]:

panel = panel.sort_values(["team_clean_name", "year"])


panel["drivers_prev"] = (# previous drivers within each team
    panel
    .groupby("team_clean_name")["drivers"]
    .shift(1)
)

panel["driver_change"] = (panel["drivers"] != panel["drivers_prev"]).astype(int) # 1 if lineup changed vs previous year, 0 otherwise


# previous year's profit and profit change
panel["profit_prev"] = (
    panel
    .groupby("team_clean_name")["profit"]
    .shift(1)
)

panel["profit_change"] = panel["profit"] - panel["profit_prev"]

# drop first year per team
reg_data = panel.dropna(subset=["profit_prev"]).copy()


reg_data[["team_clean_name", "year", "drivers", "drivers_prev",
          "driver_change", "profit_prev", "profit", "profit_change"]]


model_fe = smf.ols(
    "profit_change ~ driver_change + C(team_clean_name) + C(year)",
    data=reg_data
).fit()

print(model_fe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          profit_change   R-squared:                       0.598
Model:                            OLS   Adj. R-squared:                  0.361
Method:                 Least Squares   F-statistic:                     2.527
Date:                Tue, 02 Dec 2025   Prob (F-statistic):             0.0445
Time:                        13:14:11   Log-Likelihood:                -57.228
No. Observations:                  28   AIC:                             136.5
Df Residuals:                      17   BIC:                             151.1
Df Model:                          10
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                -0.3418      1.606     -0.213      0.834      -3.731       3.047
C(team_clean_name)[T.Alpine]             -0.2500      1.695     -0.147      0.884      -3.827       3.327
C(team_clean_name)[T.Aston Martin]        1.7500      1.695      1.032      0.316      -1.827       5.327
C(team_clean_name)[T.Ferrari]            -0.9286      1.787     -0.520      0.610      -4.699       2.842
C(team_clean_name)[T.McLaren]             0.6607      1.719      0.384      0.705      -2.965       4.287
C(team_clean_name)[T.Mercedes]           -2.6786      1.787     -1.499      0.152      -6.449       1.092
C(team_clean_name)[T.Red Bull Racing]    -1.0893      1.719     -0.634      0.535      -4.715       2.537
C(year)[T.2021]                           5.4388      1.370      3.970      0.001       2.548       8.329
C(year)[T.2022]                           2.0918      1.292      1.620      0.124      -0.633       4.817
C(year)[T.2023]                           1.9082      1.292      1.477      0.158      -0.817       4.633
driver_change                            -0.3571      1.130     -0.316      0.756      -2.742       2.027
==============================================================================
Omnibus:                        1.484   Durbin-Watson:                   2.223
Prob(Omnibus):                  0.476   Jarque-Bera (JB):                0.505
Skew:                           0.237   Prob(JB):                        0.777
Kurtosis:                       3.456   Cond. No.                         10.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

R^2 is ok, but lets find what the driver's effect is. COntrol for points...

In [20]:

fastf1.Cache.enable_cache("F1/f1_cache") 

years = sorted(set(panel["year"])) 

records = []

for year in years:
    schedule = fastf1.get_event_schedule(year, include_testing=False)

    for _, event in schedule.iterrows():
        gp_name = event["EventName"]   # 'Australian Grand Prix'
        session = fastf1.get_session(year, gp_name, "R")
        session.load()

        res = session.results

        for _, row in res.iterrows():
            records.append({
                "year": year,
                "team_f1": row["TeamName"],
                "points_race": row["Points"]
            })

team_points_raw = pd.DataFrame(records)

team_points = (
    team_points_raw
    .groupby(["team_f1", "year"], as_index=False)
    .agg(points=("points_race", "sum"))
)
team_points.head()

core           INFO 	Loading data for Australian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 77 completed the race distance 00:00.387000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '5', '16', '20', '27', '7', '18', '26', '10', '4', '11', '23', '99', '63', '88', '8', '3', '55']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.070000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '5', '4', '7', '10', '23', '11', '99', '26', '20', '18', '63', '88', '27', '3', '55', '8']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.423000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '33', '16', '10', '3', '11', '7', '23', '8', '18', '20', '55', '99', '63', '88', '4', '26', '27']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 77 completed the race distance 00:00.075000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '33', '16', '11', '55', '4', '18', '7', '23', '99', '20', '27', '63', '88', '10', '8', '26', '3']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.059000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '5', '16', '10', '20', '55', '26', '8', '23', '3', '27', '7', '11', '99', '63', '88', '18', '4']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.087000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '77', '33', '10', '55', '26', '23', '3', '8', '4', '11', '27', '20', '63', '18', '7', '88', '99', '16']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 5 completed the race distance 00:00.190000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '16', '77', '33', '3', '27', '10', '18', '26', '55', '11', '99', '8', '7', '63', '20', '88', '23', '4']
core           INFO 	Loading data for French Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.126000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '5', '55', '7', '27', '4', '10', '3', '11', '18', '26', '23', '99', '20', '88', '63', '8']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 33 completed the race distance 00:00.042000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '16', '77', '5', '44', '4', '10', '55', '7', '99', '11', '3', '27', '18', '23', '8', '26', '63', '20', '88']
core           INFO 	Loading data for British Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.042000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '10', '33', '55', '3', '7', '26', '27', '4', '23', '18', '63', '88', '5', '11', '99', '8', '20']
core           INFO 	Loading data for German Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 33 completed the race distance 00:00.090000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '5', '26', '18', '55', '23', '8', '20', '44', '88', '63', '7', '99', '10', '77', '27', '16', '4', '3', '11']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.069000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '5', '16', '55', '10', '7', '77', '4', '23', '11', '27', '20', '3', '26', '63', '18', '99', '88', '8']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 16 completed the race distance 00:00.211000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '77', '5', '23', '11', '26', '27', '10', '18', '4', '20', '8', '3', '63', '7', '88', '99', '55', '33']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 16 completed the race distance 00:00.092000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '77', '44', '3', '27', '23', '11', '33', '99', '4', '10', '18', '5', '63', '7', '8', '88', '20', '26', '55']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 5 completed the race distance 00:00.171000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['5', '16', '33', '44', '77', '23', '4', '10', '27', '99', '8', '55', '18', '3', '26', '88', '20', '7', '11', '63']
core           INFO 	Loading data for Russian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.308000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '23', '55', '11', '4', '20', '27', '18', '26', '7', '10', '99', '88', '63', '5', '3', '8']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 77 completed the race distance 00:00.224000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['77', '5', '44', '23', '55', '16', '10', '11', '18', '26', '4', '7', '8', '99', '20', '63', '88', '33', '3', '27']
core           INFO 	Loading data for Mexican Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.798000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '77', '16', '23', '33', '11', '3', '10', '27', '26', '18', '55', '99', '20', '63', '8', '88', '7', '4']
core           INFO 	Loading data for United States Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 77 completed the race distance 00:00.080000 before the recorded end of the session.

             team_f1  year  points
0         Alfa Romeo  2022    53.0
1         Alfa Romeo  2023    16.0
2  Alfa Romeo Racing  2019    57.0
3  Alfa Romeo Racing  2020     8.0
4  Alfa Romeo Racing  2021    13.0

Create an OLS model for Driver Changes realting to points

In [ ]:
# name_map from earlier
team_points["team_clean_name"] = team_points["team_f1"].map(name_map)
team_points = team_points.dropna(subset=["team_clean_name"])


panel = panel.merge(
    team_points[["team_clean_name", "year", "points"]],
    on=["team_clean_name", "year"],
    how="left"
)
#Create lagged points + points_change
panel = panel.sort_values(["team_clean_name", "year"])

panel["points_prev"] = panel.groupby("team_clean_name")["points"].shift(1)
panel["points_change"] = panel["points"] - panel["points_prev"]

#build regression dataset
reg_data = panel.dropna(subset=["profit_prev", "points_prev"]).copy()



#ols control for points
model_pts = smf.ols(
    "profit_change ~ driver_change + points_change + C(team_clean_name) + C(year)",
    data=reg_data
).fit()

print(model_pts.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          profit_change   R-squared:                       0.634
Model:                            OLS   Adj. R-squared:                  0.383
Method:                 Least Squares   F-statistic:                     2.522
Date:                Tue, 02 Dec 2025   Prob (F-statistic):             0.0453
Time:                        13:24:59   Log-Likelihood:                -55.899
No. Observations:                  28   AIC:                             135.8
Df Residuals:                      16   BIC:                             151.8
Df Model:                          11
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 0.0583      1.611      0.036      0.972      -3.356       3.473
C(team_clean_name)[T.Alpine]             -0.3454      1.668     -0.207      0.839      -3.882       3.191
C(team_clean_name)[T.Aston Martin]        1.4522      1.683      0.863      0.401      -2.116       5.020
C(team_clean_name)[T.Ferrari]            -0.9032      1.757     -0.514      0.614      -4.627       2.821
C(team_clean_name)[T.McLaren]             0.4140      1.701      0.243      0.811      -3.191       4.019
C(team_clean_name)[T.Mercedes]           -2.3927      1.771     -1.351      0.196      -6.147       1.362
C(team_clean_name)[T.Red Bull Racing]    -1.6291      1.743     -0.935      0.364      -5.324       2.065
C(year)[T.2021]                           4.9887      1.393      3.581      0.002       2.035       7.942
C(year)[T.2022]                           1.8568      1.283      1.447      0.167      -0.864       4.577
C(year)[T.2023]                           1.6783      1.283      1.308      0.209      -1.041       4.397
driver_change                            -0.4879      1.116     -0.437      0.668      -2.853       1.877
points_change                             0.0047      0.004      1.262      0.225      -0.003       0.012
==============================================================================
Omnibus:                        1.242   Durbin-Watson:                   2.356
Prob(Omnibus):                  0.538   Jarque-Bera (JB):                0.305
Skew:                           0.040   Prob(JB):                        0.859
Kurtosis:                       3.505   Cond. No.                     1.09e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.09e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

# I estimated a fixed-effects OLS model of year-over-year profit changes including controls for performance (Constructor points change), team fixed effects, and year fixed effects. The results show no statistically significant relationship between driver changes and profitability (β ≈ −0.49, p = 0.67). After controlling for performance and structural team differences, driver switches do not explain profit movements. The main drivers of profit variation are macro-level year effects, especially the rebound in 2021.