In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
from datetime import datetime
import os, time

from scipy import stats
from sklearn.linear_model import LinearRegression
from typing import Optional
from fastf1.core import Session
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.stattools import grangercausalitytests
!pip install fastf1
import fastf1 as ff1
from fastf1 import plotting



os.chdir('/Users/jackson/Documents/ECON570')

Requirement already satisfied: fastf1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (3.6.1)
Requirement already satisfied: matplotlib<4.0.0,>=3.5.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (3.8.4)
Requirement already satisfied: numpy<3.0.0,>=1.23.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=1.4.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (2.2.2)
Requirement already satisfied: python-dateutil in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (2.9.0.post0)
Requirement already satisfied: rapidfuzz in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (3.14.1)
Requirement already satisfied: requests-cache>=1.0.0 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (1.2.1)
Requirement already satisfied: requests>=2.28.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.8.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (1.15.3)
Requirement already satisfied: timple>=0.1.6 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (0.1.8)
Requirement already satisfied: websockets<14,>=10.3 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from fastf1) (13.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (25.0)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from pandas<3.0.0,>=1.4.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from pandas<3.0.0,>=1.4.1->fastf1) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests>=2.28.1->fastf1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests>=2.28.1->fastf1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests>=2.28.1->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests>=2.28.1->fastf1) (2025.8.3)
Requirement already satisfied: attrs>=21.2 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (4.3.7)
Requirement already satisfied: url-normalize>=1.4 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from requests-cache>=1.0.0->fastf1) (2.2.1)
Requirement already satisfied: exceptiongroup>=1.1.1 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (1.2.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /opt/anaconda3/envs/econ570/lib/python3.10/site-packages (from cattrs>=22.2->requests-cache>=1.0.0->fastf1) (4.15.0)

In [ ]:
ff1.Cache.enable_cache("F1/f1_cache")  # or your existing path

years = range(2014, 2024)  # example window

records = []

for year in years:
    # You might want to be explicit about the race; here I assume Bahrain
    session = ff1.get_session(year, "Bahrain Grand Prix", "R")
    session.load()

    for drv in session.drivers:
        d = session.get_driver(drv)
        records.append({
            "year": year,
            "team_f1": d["TeamName"],     # e.g. 'Mercedes', 'McLaren'
            "driver_code": d["Abbreviation"],  # 'HAM', 'NOR', etc.
            "driver_name": d["FullName"]
        })

driver_year_df = pd.DataFrame(records)

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO 	Finished loading data for 22 drivers: ['44', '6', '11', '3', '27', '1', '19', '77', '14', '7', '26', '8', '4', '13', '10', '17', '22', '20', '21', '9', '25', '99']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO 	Finished loading data for 20 drivers: ['44', '7', '6', '77', '5', '3', '8', '11', '26', '19', '14', '12', '27', '9', '13', '28', '98', '33', '55', '22']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO 	Finished loading data for 22 drivers: ['6', '7', '44', '3', '8', '33', '26', '19', '77', '47', '20', '9', '94', '12', '27', '11', '88', '55', '21', '22', '5', '30']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '77', '7', '3', '19', '11', '8', '27', '31', '94', '26', '30', '14', '9', '55', '18', '33', '20', '2']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!
core        WARNING 	Failed to determine `Session.t0_date`!
logger      WARNING 	Failed to load telemetry data!
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['5', '77', '44', '10', '20', '27', '14', '2', '9', '31', '55', '16', '8', '18', '35', '11', '28', '7', '33', '3']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.070000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '5', '4', '7', '10', '23', '11', '99', '26', '20', '18', '63', '88', '27', '3', '55', '8']
events      WARNING 	Correcting user input 'Bahrain Grand Prix' to 'Bahrain Grand Prix'
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '23', '4', '55', '10', '3', '77', '31', '16', '26', '63', '5', '6', '7', '99', '20', '11', '18', '8']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.067000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '4', '11', '16', '3', '55', '22', '18', '7', '99', '31', '63', '5', '47', '10', '6', '14', '9']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 16 completed the race distance 00:00.050000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '44', '63', '20', '77', '31', '22', '14', '24', '47', '18', '23', '3', '4', '6', '27', '11', '1', '10']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

In [10]:
team_lineups = (
    driver_year_df
    .groupby(["team_f1", "year"])["driver_code"]
    .apply(lambda x: tuple(sorted(set(x))))
    .reset_index(name="drivers")
)

In [11]:
team_lineups = team_lineups.sort_values(["team_f1", "year"])

team_lineups["drivers_prev"] = (
    team_lineups
    .groupby("team_f1")["drivers"]
    .shift(1)
)

team_lineups["driver_change"] = (
    (team_lineups["drivers"] != team_lineups["drivers_prev"])
    .astype(int)
)

In [17]:
name_map = {
    "Mercedes": "Mercedes",       # or 'Mercedes-Benz Grand Prix Ltd'
    "McLaren": "McLaren",
    "Ferrari": "Ferrari",
    "Red Bull Racing": "Red Bull",  # etc.
    # add others
}

team_lineups["team_clean_name"] = team_lineups["team_f1"].map(name_map)

In [20]:
profits_df = pd.read_csv("F1/f1_financial_data.csv")
profits_df.head()

profits_df = pd.read_csv("F1/f1_financial_data.csv")

profits_df = profits_df.rename(columns={
    "Team": "team_clean_name",
    "Year": "year",
    "Operating Profit (£m)": "profit"      # choose this as your main profit metric
})

profits_df.head()
panel = team_lineups.merge(
    profits_df,
    on=["team_clean_name", "year"],
    how="inner"
)

# Profit change vs previous season within a team
panel = panel.sort_values(["team_clean_name", "year"])

panel["profit_prev"] = (
    panel
    .groupby("team_clean_name")["profit"]
    .shift(1)
)

panel["profit_change"] = panel["profit"] - panel["profit_prev"]

panel.head()

,team_f1,year,drivers,drivers_prev,driver_change,team_clean_name,Legal Entity,Country,Revenue (£m),profit,Net Income (£m),Prize Money (£m),Employees,Source,profit_prev,profit_change
0,Ferrari,2019,"(LEC, VET)","(RAI, VET)",1,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,380,13,10,180,950,Ferrari Annual Report,NaN,NaN
1,Ferrari,2020,"(LEC, VET)","(LEC, VET)",0,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,350,9,7,165,930,NaN,13.0,-4.0
2,Ferrari,2021,"(LEC, SAI)","(LEC, VET)",1,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,365,12,9,170,940,NaN,9.0,3.0
3,Ferrari,2022,"(LEC, SAI)","(LEC, SAI)",0,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,392,15,12,178,960,NaN,12.0,3.0
4,Ferrari,2023,"(LEC, SAI)","(LEC, SAI)",0,Ferrari,Gestione Sportiva (Ferrari S.p.A.),Italy,405,17,13,180,970,NaN,15.0,2.0

In [29]:
# Example, adjust based on actual FastF1 team names you see in team_lineups['team_f1'].unique()

name_map = {
    # Sauber lineage
    "Sauber": "Alfa Romeo",
    "Alfa Romeo Racing": "Alfa Romeo",
    "Alfa Romeo": "Alfa Romeo",

    # Toro Rosso / AlphaTauri lineage
    "Toro Rosso": "AlphaTauri",
    "AlphaTauri": "AlphaTauri",

    # Renault / Lotus / Alpine lineage
    "Renault": "Alpine",
    "Lotus F1": "Alpine",
    "Alpine": "Alpine",

    # Force India / Racing Point / Aston Martin lineage
    "Force India": "Aston Martin",
    "Racing Point": "Aston Martin",
    "Aston Martin": "Aston Martin",

    # Red Bull lineage
    "Red Bull": "Red Bull Racing",
    "Red Bull Racing": "Red Bull Racing",

    # Marussia / Manor
    "Marussia": "Manor Marussia",
    "Manor Marussia": "Manor Marussia",

    # Stable names
    "Ferrari": "Ferrari",
    "McLaren": "McLaren",
    "Mercedes": "Mercedes",
    "Haas F1 Team": "Haas F1 Team",
    "Caterham": "Caterham",}

team_lineups["team_clean_name"] = (
    team_lineups["team_f1"].map(name_map).fillna(team_lineups["team_f1"])
)

team_lineups[["team_f1", "team_clean_name"]].drop_duplicates().sort_values("team_f1")



team_lineups["team_clean_name"] = team_lineups["team_f1"].map(name_map)

In [30]:
print(team_lineups.columns)
print(team_lineups[["team_f1", "team_clean_name"]].drop_duplicates().head(20))

Index(['team_f1', 'year', 'drivers', 'drivers_prev', 'driver_change',
       'team_clean_name'],
      dtype='object')
              team_f1  team_clean_name
0          Alfa Romeo       Alfa Romeo
2   Alfa Romeo Racing       Alfa Romeo
5          AlphaTauri       AlphaTauri
9              Alpine           Alpine
12       Aston Martin     Aston Martin
15           Caterham         Caterham
16            Ferrari          Ferrari
26        Force India     Aston Martin
31       Haas F1 Team     Haas F1 Team
39           Lotus F1           Alpine
41     Manor Marussia   Manor Marussia
43           Marussia   Manor Marussia
44            McLaren          McLaren
54           Mercedes         Mercedes
64       Racing Point     Aston Martin
66           Red Bull  Red Bull Racing
70    Red Bull Racing  Red Bull Racing
76            Renault           Alpine
81             Sauber       Alfa Romeo
86         Toro Rosso       AlphaTauri

In [31]:
    panel = team_lineups.merge(
    profits_df[["team_clean_name", "year", "profit", "Revenue (£m)", "Net Income (£m)"]],
    on=["team_clean_name", "year"],
    how="inner"
)

In [34]:
panel[["team_clean_name", "year", "drivers", "profit"]]

    team_clean_name  year     drivers  profit
0        AlphaTauri  2020  (GAS, KVY)       1
1        AlphaTauri  2021  (GAS, TSU)       2
2        AlphaTauri  2022  (GAS, TSU)       3
3        AlphaTauri  2023  (DEV, TSU)       4
4            Alpine  2021  (ALO, OCO)       1
5            Alpine  2022  (ALO, OCO)       3
6            Alpine  2023  (GAS, OCO)       4
7      Aston Martin  2021  (STR, VET)       2
8      Aston Martin  2022  (HUL, STR)       5
9      Aston Martin  2023  (ALO, STR)       8
10          Ferrari  2019  (LEC, VET)      13
11          Ferrari  2020  (LEC, VET)       9
12          Ferrari  2021  (LEC, SAI)      12
13          Ferrari  2022  (LEC, SAI)      15
14          Ferrari  2023  (LEC, SAI)      17
15          McLaren  2019  (NOR, SAI)      -2
16          McLaren  2020  (NOR, SAI)      -5
17          McLaren  2021  (NOR, RIC)       3
18          McLaren  2022  (NOR, RIC)       5
19          McLaren  2023  (NOR, PIA)       8
20         Mercedes  2019  (BOT, HAM)      18
21         Mercedes  2020  (BOT, HAM)      16
22         Mercedes  2021  (BOT, HAM)      22
23         Mercedes  2022  (HAM, RUS)      19
24         Mercedes  2023  (HAM, RUS)      15
25     Aston Martin  2019  (PER, STR)      -6
26     Aston Martin  2020  (PER, STR)      -4
27  Red Bull Racing  2019  (GAS, VER)       4
28  Red Bull Racing  2020  (ALB, VER)       2
29  Red Bull Racing  2021  (PER, VER)       5
30  Red Bull Racing  2022  (PER, VER)       6
31  Red Bull Racing  2023  (PER, VER)       7
32           Alpine  2019  (HUL, RIC)      -2
33           Alpine  2020  (OCO, RIC)      -3
34       AlphaTauri  2019  (ALB, KVY)      -3

In [36]:

# assuming `panel` is the df you printed
panel = panel.sort_values(["team_clean_name", "year"])

# previous drivers within each team
panel["drivers_prev"] = (
    panel
    .groupby("team_clean_name")["drivers"]
    .shift(1)
)

# 1 if lineup changed vs previous year, 0 otherwise
panel["driver_change"] = (panel["drivers"] != panel["drivers_prev"]).astype(int)

# previous year's profit and profit change
panel["profit_prev"] = (
    panel
    .groupby("team_clean_name")["profit"]
    .shift(1)
)

panel["profit_change"] = panel["profit"] - panel["profit_prev"]

# drop first year per team (no lag)
reg_data = panel.dropna(subset=["profit_prev"]).copy()


reg_data[["team_clean_name", "year", "drivers", "drivers_prev",
          "driver_change", "profit_prev", "profit", "profit_change"]]


model_fe = smf.ols(
    "profit_change ~ driver_change + C(team_clean_name) + C(year)",
    data=reg_data
).fit()

print(model_fe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          profit_change   R-squared:                       0.598
Model:                            OLS   Adj. R-squared:                  0.361
Method:                 Least Squares   F-statistic:                     2.527
Date:                Thu, 20 Nov 2025   Prob (F-statistic):             0.0445
Time:                        11:30:54   Log-Likelihood:                -57.228
No. Observations:                  28   AIC:                             136.5
Df Residuals:                      17   BIC:                             151.1
Df Model:                          10
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                -0.3418      1.606     -0.213      0.834      -3.731       3.047
C(team_clean_name)[T.Alpine]             -0.2500      1.695     -0.147      0.884      -3.827       3.327
C(team_clean_name)[T.Aston Martin]        1.7500      1.695      1.032      0.316      -1.827       5.327
C(team_clean_name)[T.Ferrari]            -0.9286      1.787     -0.520      0.610      -4.699       2.842
C(team_clean_name)[T.McLaren]             0.6607      1.719      0.384      0.705      -2.965       4.287
C(team_clean_name)[T.Mercedes]           -2.6786      1.787     -1.499      0.152      -6.449       1.092
C(team_clean_name)[T.Red Bull Racing]    -1.0893      1.719     -0.634      0.535      -4.715       2.537
C(year)[T.2021]                           5.4388      1.370      3.970      0.001       2.548       8.329
C(year)[T.2022]                           2.0918      1.292      1.620      0.124      -0.633       4.817
C(year)[T.2023]                           1.9082      1.292      1.477      0.158      -0.817       4.633
driver_change                            -0.3571      1.130     -0.316      0.756      -2.742       2.027
==============================================================================
Omnibus:                        1.484   Durbin-Watson:                   2.223
Prob(Omnibus):                  0.476   Jarque-Bera (JB):                0.505
Skew:                           0.237   Prob(JB):                        0.777
Kurtosis:                       3.456   Cond. No.                         10.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

R^2 is ok, but lets find what the driver's effect is. COntrol for points...

In [39]:

ff1.Cache.enable_cache("F1/f1_cache")  # or your cache path

years = sorted(panel["year"].unique())  # from your existing panel

records = []

for year in years:
    schedule = ff1.get_event_schedule(year)
    for rnd in schedule["RoundNumber"].unique():
        session = ff1.get_session(year, int(rnd), "R")
        session.load()
        res = session.results  # DataFrame

        for _, row in res.iterrows():
            records.append({
                "year": year,
                "team_f1": row["TeamName"],
                "points_race": row["Points"]
            })

team_points_raw = pd.DataFrame(records)

# sum across races to get season total
team_points = (
    team_points_raw
    .groupby(["team_f1", "year"], as_index=False)["points_race"]
    .sum()
    .rename(columns={"points_race": "points"})
)

core           INFO 	Loading data for Australian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 77 completed the race distance 00:00.387000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '5', '16', '20', '27', '7', '18', '26', '10', '4', '11', '23', '99', '63', '88', '8', '3', '55']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.070000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '5', '4', '7', '10', '23', '11', '99', '26', '20', '18', '63', '88', '27', '3', '55', '8']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.423000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '33', '16', '10', '3', '11', '7', '23', '8', '18', '20', '55', '99', '63', '88', '4', '26', '27']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 77 completed the race distance 00:00.075000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '33', '16', '11', '55', '4', '18', '7', '23', '99', '20', '27', '63', '88', '10', '8', '26', '3']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.059000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '5', '16', '10', '20', '55', '26', '8', '23', '3', '27', '7', '11', '99', '63', '88', '18', '4']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.087000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '77', '33', '10', '55', '26', '23', '3', '8', '4', '11', '27', '20', '63', '18', '7', '88', '99', '16']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 5 completed the race distance 00:00.190000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '16', '77', '33', '3', '27', '10', '18', '26', '55', '11', '99', '8', '7', '63', '20', '88', '23', '4']
core           INFO 	Loading data for French Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.126000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '5', '55', '7', '27', '4', '10', '3', '11', '18', '26', '23', '99', '20', '88', '63', '8']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 33 completed the race distance 00:00.042000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '16', '77', '5', '44', '4', '10', '55', '7', '99', '11', '3', '27', '18', '23', '8', '26', '63', '20', '88']
core           INFO 	Loading data for British Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.042000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '10', '33', '55', '3', '7', '26', '27', '4', '23', '18', '63', '88', '5', '11', '99', '8', '20']
core           INFO 	Loading data for German Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 33 completed the race distance 00:00.090000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '5', '26', '18', '55', '23', '8', '20', '44', '88', '63', '7', '99', '10', '77', '27', '16', '4', '3', '11']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 44 completed the race distance 00:00.069000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '5', '16', '55', '10', '7', '77', '4', '23', '11', '27', '20', '3', '26', '63', '18', '99', '88', '8']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 16 completed the race distance 00:00.211000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '77', '5', '23', '11', '26', '27', '10', '18', '4', '20', '8', '3', '63', '7', '88', '99', '55', '33']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 16 completed the race distance 00:00.092000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['16', '77', '44', '3', '27', '23', '11', '33', '99', '4', '10', '18', '5', '63', '7', '8', '88', '20', '26', '55']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 5 completed the race distance 00:00.171000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['5', '16', '33', '44', '77', '23', '4', '10', '27', '99', '8', '55', '18', '3', '26', '88', '20', '7', '11', '63']
core           INFO 	Loading data for Russian Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 44 completed the race distance 00:00.308000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '16', '33', '23', '55', '11', '4', '20', '27', '18', '26', '7', '10', '99', '88', '63', '5', '3', '8']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...

ValueError: Cannot get testing event by round number!