 
 <div style="margin-top:40px;"></div>

<!-- Prof & TA Information -->
<div style="display:flex; justify-content:space-between;">
    
<div style="width:70%;">
<strong>Professor: </strong> Ashley T. Swanson<br>
OH: TR 2:15 - 3:15 | 7434 Sewell Social Sciences <br>
Email: ashley.swanson@wisc.edu
</div>
    
<div style="width:100%:right;">
<strong>TA: </strong> Alejandro Herrera-Caicedo <br>
OH: TR 4:00 - 5:00 | 7310 Social Sciences<br>
Email: herreracaice@wisc.edu
</div>
</div>

---

<!-- Title + Subtitle -->
<div style="padding:25px; 
            text-align:center; 
            font-size:3em; 
            font-weight:bold;
            margin-bottom:5px;">
  Discussion 3 <br>
  <div style="font-size:0.4em; 
              font-weight:normal;
              margin-top:8px; 
              font-style:italic;
              margin-bottom:10px;">
  Econ 570 – September 26, 2025
  </div>
</div>

<!-- Reminder Box -->
<div style="background-color:#B22222; 
            color:white; 
            padding:15px 25px; 
            border-radius:8px; 
            text-align:center; 
            font-size:1.2em; 
            font-family: Arial, Helvetica, sans-serif;
            font-weight:bold;
            margin-bottom:10px;">
 Reminder: Discussion Post is due tonight!
</div>

<!-- Header for plan for today -->

<div style="padding:10px; 
            text-align:justify; 
            font-size:2em; 
            margin-bottom:5px;">
  Plan for Today </div>

1. A quick note on method chaining.
2. Merging stacking and concatenating.
3. Lambda Functions.
4. String Methods


**Files needed:** `WEOOct2021all.csv` ([⬇️](https://canvas.wisc.edu/courses/479130/files/46712373/download?download_frd=1))

In [5]:
#///////////////////////////////////////////////////////////////////////////////
#----  Load the libraries for today                                         ----
#///////////////////////////////////////////////////////////////////////////////
import pandas as pd
import warnings
warnings.filterwarnings("ignore", category=pd.errors.PerformanceWarning) # Suppress performance warning for indicator = True in pd.merge()
import os

os.chdir('/Users/jackson/Documents/ECON570')

# 1. Note on [method chaining](https://medium.com/@ulriktpedersen/modern-pandas-streamlining-your-workflow-with-method-chaining-f65e75deb193)
Method chaining, exemplified in the first data frame created below, is an efficient and clean way to write your Pandas cleaning and wrangling tasks. Becoming proficient at method chaining can make your code much more readable. One opens a method chain using the following syntax,
```python
MyDf = (
  # a series of pandas methods go here
)
```

In [6]:
df = pd.read_csv('data/WEOOct2021all.csv', index_col=['ISO','Variable'])
df.head()

                                           Description           Units  1980  \
ISO Variable
AFG Surplus   General government net lending/borrowing  Percent of GDP   NaN
    Debt                 General government gross debt  Percent of GDP   NaN
ALB Surplus   General government net lending/borrowing  Percent of GDP   NaN
    Debt                 General government gross debt  Percent of GDP   NaN
DZA Surplus   General government net lending/borrowing  Percent of GDP   NaN

              1981  1982  1983  1984  1985  1986  1987  ...    2017    2018  \
ISO Variable                                            ...
AFG Surplus    NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...  -0.673   1.634
    Debt       NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   7.998   7.384
ALB Surplus    NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...  -1.392  -1.346
    Debt       NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...  71.895  69.509
DZA Surplus    NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...  -6.541  -4.426

                2019    2020    2021    2022    2023    2024    2025    2026
ISO Variable
AFG Surplus   -1.058  -2.243     NaN     NaN     NaN     NaN     NaN     NaN
    Debt       6.130   7.397     NaN     NaN     NaN     NaN     NaN     NaN
ALB Surplus   -1.959  -6.864  -6.694  -5.279  -3.734  -2.549  -2.220  -1.949
    Debt      67.792  77.568  81.475  79.471  79.160  77.740  75.297  73.351
DZA Surplus   -5.579  -6.248  -9.246  -6.519  -6.043  -5.864  -6.043  -6.139

[5 rows x 49 columns]

We will reshape the data so that each country is an unique observation and variables are columns. For this we will use stacking and unstacking.

<div style="text-align: center;">
  <img src="https://miro.medium.com/v2/resize:fit:1050/1*DYDOif_qBEgtWfFKUDSf0Q.png" 
       alt="Join types in SQL/Pandas" 
       style="width: 500px;"/>
  <p style="font-size: 0.9em; color: gray;">
    Stacking and Unstacking
  </p>
  <p style="font-size: 0.9em; color: gray;">
    Source: YeeJay's Medium (<a href="https://medium.com/data-science/reshaping-a-dataframe-with-pandas-stack-and-unstack-925dc9ce1289">link</a>)
  </p>
</div>

Instad of performing all the operations line by line, we will use method chaining. The inherent downside is that you cant inspect each stage!

In [7]:

df = (df
    .drop(columns=['Description','Units'])       # Drop 'meta-data' columns
    .stack()                                     # Reshape long. This first stack turns the yearly columns into rows.
    .unstack('Variable')                         # Reshape wide. The secon stack turns the variables into columns.
    .rename_axis(index={None:'Year'})            # Label the second dimension of the row index to year
    .rename_axis(columns={'Variable':None})      # Remove the 'Variable' index name
    .sort_index(axis=0)
)

df

            Debt  Surplus
ISO Year
ABW 1995  55.088   -0.834
    1996  54.771   -2.343
    1997  51.070   -2.102
    1998  41.039    0.114
    1999  39.288    0.086
...          ...      ...
ZWE 2022  60.311   -0.594
    2023  62.027   -1.046
    2024  62.240   -1.095
    2025  60.688   -1.093
    2026  59.609   -1.084

[6808 rows x 2 columns]

# 2. To Merge or to Stack and Concatenate? &#x1F914;

<div style="display: flex; gap: 20px; justify-content: center;">
  <div style="text-align: center;">
    <img src="https://towardsdatascience.com/wp-content/uploads/2020/06/10wu6DunCzPC4o9FIyRTW4w.png" 
         alt="Concatenating" 
         style="width: 500px;"/>
    <p style="font-size: 0.9em; color: gray;">
      Concatenating
    </p>
  </div>

  <div style="text-align: center;">
    <img src="https://towardsdatascience.com/wp-content/uploads/2020/06/1-uSHoxrzM57syqnKnms2iA.png" 
         alt="Merging" 
         style="width: 500px;"/>
    <p style="font-size: 0.9em; color: gray;">
      Merging
    </p>
  </div>

<div style="display: flex; flex-direction: column; align-items: center;">
    <p style="font-size: 0.9em; color: gray; margin-top: 10px;">
    Source: "3 Key Differences between Merge and Concat Functions of Pandas" - Towards Data Science (<a href="https://towardsdatascience.com/3-key-differences-between-merge-and-concat-functions-of-pandas-ab2bab224b59/">link</a>)
    </p>
</div>


Suppose, that we want to illustrate the growth of debt and surplus by country from 2000 to 2001 as follows (values are illustrative):

| Country   | Debt (2000) | Surplus (2000) | Debt (2001) | Surplus (2001) | Debt Growth | Surplus Growth |
|-----------|-------------|----------------|-------------|----------------|-------------|----------------|
| USA       | 100         | 20             | 120         | 30             | 20%         | 50%            |
| Canada    | 80          | 25             | 90          | 20             | 12.5%       | -20%           |
| Mexico    | 70          | 35             | 75          | 25             | 7.1%        | -28.6%         |



However, assume that our starting point are two datasets: one for debt in 2000 and 2001 and another one for the surplus in the same years.

In [8]:
# Creating the messy dataset part 1: df_wide_debt
df_wide_debt = (
    df.loc[df.index.get_level_values('Year').isin(['2000','2001'])] # Subset to years in 2000-2001
    .drop(columns='Surplus')                                        # Drop the surplus column
    .unstack()                                                      # Unstack the debt!
    .rename_axis(columns={'Year':None})                             # Rename the index
)
df_wide_debt.head()

        Debt
        2000     2001
ISO
ABW   38.613   44.326
AGO  133.914  113.505
ALB   63.769   60.613
AND      NaN   15.773
ARE    3.093    2.690

In [9]:
# Creating the messy dataset part 2: df_wide_surplus
df_wide_surplus = (
    df.loc[df.index.get_level_values('Year').isin(['2000','2001'])] #Subset to years in 2000-2001
    .drop(columns='Debt')                                           #Drop the debt column
    .unstack()                                                      #Unstack the surplus!
    .rename_axis(columns={'Year':None})                             #Rename the index
)
df_wide_surplus.head()

    Surplus
       2000   2001
ISO
ABW   0.645 -0.835
AGO   2.289  3.176
ALB  -7.772 -6.837
AND     NaN  0.652
ARE  10.567  1.205

Now, we would like to turn this into a useful dataset. As we saw last week, we can merge these two data frames into one wide data frame using 
```python
pd.merge()
```

In [10]:
Wide_df = pd.merge(df_wide_debt, df_wide_surplus, how = 'outer', on = 'ISO', indicator = True)
Wide_df

        Debt          Surplus        _merge
        2000     2001    2000   2001
ISO
ABW   38.613   44.326   0.645 -0.835   both
AGO  133.914  113.505   2.289  3.176   both
ALB   63.769   60.613  -7.772 -6.837   both
AND      NaN   15.773     NaN  0.652   both
ARE    3.093    2.690  10.567  1.205   both
..       ...      ...     ...    ...    ...
WBG   20.024   22.159     NaN    NaN   both
WSM   57.207   55.170  -0.632 -2.008   both
YEM   60.841   60.569   6.087  2.787   both
ZAF   37.929   38.045  -1.383 -1.015   both
ZMB  260.964  210.243   1.161 -5.892   both

[184 rows x 5 columns]

Recall that you can check how the merge went by checking the values of the `'_merge'` column created by setting `indicator = True`

In [11]:
Wide_df['_merge'].value_counts()

_merge
both          184
left_only       0
right_only      0
Name: count, dtype: int64

Great! All observations were in both datasets.

In [12]:
# Drop _merge; overwrite in place
Wide_df.drop(columns=['_merge'],inplace=True)

In [13]:
vars_array = Wide_df.columns.droplevel(1).unique()
vars_array
Wide_df.columns

MultiIndex([(   'Debt', '2000'),
            (   'Debt', '2001'),
            ('Surplus', '2000'),
            ('Surplus', '2001')],
           )

In [14]:
# Compute the debt
for var in vars_array:
    Wide_df[(var, "Growth")] = 1 - Wide_df[(var, '2001')]/Wide_df[(var, '2000')]

Wide_df.head()

        Debt          Surplus             Debt   Surplus
        2000     2001    2000   2001    Growth    Growth
ISO
ABW   38.613   44.326   0.645 -0.835 -0.147955  2.294574
AGO  133.914  113.505   2.289  3.176  0.152404 -0.387505
ALB   63.769   60.613  -7.772 -6.837  0.049491  0.120304
AND      NaN   15.773     NaN  0.652       NaN       NaN
ARE    3.093    2.690  10.567  1.205  0.130294  0.885966

In [15]:

Wide_df = Wide_df.sort_index(axis=1, level=0)
Wide_df.head()

        Debt                    Surplus
        2000     2001    Growth    2000   2001    Growth
ISO
ABW   38.613   44.326 -0.147955   0.645 -0.835  2.294574
AGO  133.914  113.505  0.152404   2.289  3.176 -0.387505
ALB   63.769   60.613  0.049491  -7.772 -6.837  0.120304
AND      NaN   15.773       NaN     NaN  0.652       NaN
ARE    3.093    2.690  0.130294  10.567  1.205  0.885966

In [16]:

Wide_df = Wide_df.sort_index(axis=1, level=0)
Wide_df.head()

        Debt                    Surplus
        2000     2001    Growth    2000   2001    Growth
ISO
ABW   38.613   44.326 -0.147955   0.645 -0.835  2.294574
AGO  133.914  113.505  0.152404   2.289  3.176 -0.387505
ALB   63.769   60.613  0.049491  -7.772 -6.837  0.120304
AND      NaN   15.773       NaN     NaN  0.652       NaN
ARE    3.093    2.690  0.130294  10.567  1.205  0.885966

In [17]:
#If you dont like multi_indexes you can flaten them
Wide_df.columns = ['_'.join(col) 
                   for col in Wide_df.columns.to_flat_index()]
Wide_df.head()

,Debt_2000,Debt_2001,Debt_Growth,Surplus_2000,Surplus_2001,Surplus_Growth
ISO,,,,,,
ABW,38.613,44.326,-0.147955,0.645,-0.835,2.294574
AGO,133.914,113.505,0.152404,2.289,3.176,-0.387505
ALB,63.769,60.613,0.049491,-7.772,-6.837,0.120304
AND,NaN,15.773,NaN,NaN,0.652,NaN
ARE,3.093,2.690,0.130294,10.567,1.205,0.885966

# Exercise &#x1F4DA;

Last week, we saw that there are various kinds of merges. In the above we used an outer merge. Now, let's try a left merge. 
1. Are the outputs the same or different? Why?

Recall that you can check how the merge went by checking the values of the `'_merge'` column created by setting `indicator = True`

SyntaxError: invalid syntax (3226613581.py, line 5)

## An Alternative: Stacking and Concatenating
We may also notice that if the two wide data frames, `df_wide_surplus` and `df_wide_debt` were in long format, then concatenating them along the columns would generate equivalent output to a merge. Let's see this in action

In [19]:
df_long_surplus = df_wide_surplus.stack()
print(df_long_surplus.head())

#Melt alternative
df_long_surplus = (
    df_wide_surplus
    .droplevel(0, axis=1)  
    .reset_index()                      
    .melt(id_vars=["ISO"],           
          var_name="Year",          
          value_name="Surplus")  
    .set_index(['ISO','Year'])      
)

df_long_surplus.sort_index(ascending=False)

          Surplus
ISO
ABW 2000    0.645
    2001   -0.835
AGO 2000    2.289
    2001    3.176
ALB 2000   -7.772

/var/folders/p7/dtlz136x1b5bmnvrgrl428wh0000gn/T/ipykernel_33836/2894332219.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_long_surplus = df_wide_surplus.stack()

          Surplus
ISO Year
ZMB 2001   -5.892
    2000    1.161
ZAF 2001   -1.015
    2000   -1.383
YEM 2001    2.787
...           ...
ALB 2000   -7.772
AGO 2001    3.176
    2000    2.289
ABW 2001   -0.835
    2000    0.645

[368 rows x 1 columns]

In [20]:
df_long_debt =  df_wide_debt.stack()
df_long_debt

#Melt alternative
df_long_debt = (
    df_wide_debt
    .droplevel(0, axis=1)  
    .reset_index()                      
    .melt(id_vars=["ISO"],           
          var_name="Year",          
          value_name="Debt")  
    .set_index(['ISO','Year'])      
)

df_long_debt.sort_index(ascending=False)

/var/folders/p7/dtlz136x1b5bmnvrgrl428wh0000gn/T/ipykernel_33836/2569222299.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_long_debt =  df_wide_debt.stack()

             Debt
ISO Year
ZMB 2001  210.243
    2000  260.964
ZAF 2001   38.045
    2000   37.929
YEM 2001   60.569
...           ...
ALB 2000   63.769
AGO 2001  113.505
    2000  133.914
ABW 2001   44.326
    2000   38.613

[368 rows x 1 columns]

In [21]:
df_long_concat = pd.concat([df_long_debt,df_long_surplus], axis = 1) # Concatenate along axis 1
df_long_concat

             Debt  Surplus
ISO Year
ABW 2000   38.613    0.645
AGO 2000  133.914    2.289
ALB 2000   63.769   -7.772
AND 2000      NaN      NaN
ARE 2000    3.093   10.567
...           ...      ...
WBG 2001   22.159      NaN
WSM 2001   55.170   -2.008
YEM 2001   60.569    2.787
ZAF 2001   38.045   -1.015
ZMB 2001  210.243   -5.892

[368 rows x 2 columns]

Indeed &#x1F4A1;, we may recover `Wide_df` by unstacking this dataset

In [22]:
Wide_df_unstacked = df_long_concat.unstack()
Wide_df_unstacked

         Debt          Surplus
Year     2000     2001    2000   2001
ISO
ABW    38.613   44.326   0.645 -0.835
AGO   133.914  113.505   2.289  3.176
ALB    63.769   60.613  -7.772 -6.837
AND       NaN   15.773     NaN  0.652
ARE     3.093    2.690  10.567  1.205
..        ...      ...     ...    ...
WBG    20.024   22.159     NaN    NaN
WSM    57.207   55.170  -0.632 -2.008
YEM    60.841   60.569   6.087  2.787
ZAF    37.929   38.045  -1.383 -1.015
ZMB   260.964  210.243   1.161 -5.892

[184 rows x 4 columns]

**Note:** In this case, `concat` behaves like a `merge` because the two DataFrames share the same index (e.g., country or country–year). Both operations align observations based on the index labels.   However, if the indexes differ, `merge` and `concat` can yield different results depending on how the join is specified.

# Exercise &#x1F4DA;
The data frame `Wide_df_unstacked` is not exactly the same as `Wide_df` because it has stored the name of the second level of the column index as `'Year'`. Remove this name so that `Wide_df` and `Wide_df_unstacked` are exactly the same.

*Hint:* See the method chain at the very top of this notebook. There is a method in that chain which will help you complete this exercise.

In [41]:
# YOUR CODE HERE
Wide_df_unstacked = Wide_df_unstacked.rename_axis(columns={None: None})
Wide_df_unstacked

         Debt          Surplus
Year     2000     2001    2000   2001
ISO
ABW    38.613   44.326   0.645 -0.835
AGO   133.914  113.505   2.289  3.176
ALB    63.769   60.613  -7.772 -6.837
AND       NaN   15.773     NaN  0.652
ARE     3.093    2.690  10.567  1.205
..        ...      ...     ...    ...
WBG    20.024   22.159     NaN    NaN
WSM    57.207   55.170  -0.632 -2.008
YEM    60.841   60.569   6.087  2.787
ZAF    37.929   38.045  -1.383 -1.015
ZMB   260.964  210.243   1.161 -5.892

[184 rows x 4 columns]

# Lambda Functions, .map() and Grouping &#x1F5FA;
e often need to apply operations element-wise on the columns of a DataFrame.  
The `.map()` method is a powerful way to work element-wise with a pandas Series.  

For example, suppose we want to create a new variable in `df` that measures how atypical the **surplus** or the **debt** values are. One way to do this is by computing their *z-scores*.

In [24]:
df_copy = df.copy()

for var in ['Debt', 'Surplus']:
    x_mean = df[var].mean()
    x_std = df[var].std()
    df_copy[var + '_zscore'] = df["Debt"].map(lambda x: (x-x_mean)/x_std)

df_copy.head()

            Debt  Surplus  Debt_zscore  Surplus_zscore
ISO Year
ABW 1995  55.088   -0.834    -0.045522        4.325431
    1996  54.771   -2.343    -0.052795        4.301787
    1997  51.070   -2.102    -0.137704        4.025736
    1998  41.039    0.114    -0.367837        3.277544
    1999  39.288    0.086    -0.408009        3.146940

How did pandas do this? Well, `.map()` can accept a python function and apply it element wise to a series. The syntax
```python
lambda x: (x-x_mean)/x_std
```
is shorthand for a formal function definition;
```python
def f(x):
    (x-x_mean)/x_std
```
Indeed, we can write
```python
f = lambda x: (x-x_mean)/x_std
```
to store the function. To see this, consider

In [25]:
x_mean = df['Debt'].mean()
x_std = df['Debt'].std()

f = lambda x: (x-x_mean)/x_std
f(50)

-0.16225229368515234

Functions written in such a way are called *lambda functions.* The important thing to realize is that `.map()` can accept any function and a *lambda function* is just a particularly concise way of writing that function. For example we could have calculated the square of surplus in the following way.

In [26]:
mu = df["Surplus"].mean()
sigma = df["Surplus"].std(ddof=1)

def z_map(v):
    return (v - mu) / sigma

df_copy = df.copy()
df_copy['Surplus_zscore'] = df_copy['Surplus'].map(z_map)

Often we like to perform operations at an aggregate level, for which we use `.groupby()`

In [27]:
year_stats =  df['Debt'].groupby("Year").agg(['mean','std'])
year_stats.rename(columns = {'mean':'Mean_debt', 'std':'Std_debt'}, inplace=True)
year_stats.head()

      Mean_debt   Std_debt
Year
1980  47.304182  37.782382
1981  56.848455  58.412385
1982  60.558083  66.844859
1983  63.600167  66.444652
1984  72.562692  67.112302

In [28]:

merged = df.merge(
    year_stats, 
    left_on="Year",        # use 'Year' level from MultiIndex
    right_index=True,      # match it to right's index
    how="left"
)

merged.head()

            Debt  Surplus  Mean_debt   Std_debt
ISO Year
ABW 1995  55.088   -0.834  59.230258  39.320475
    1996  54.771   -2.343  54.304031  36.582729
    1997  51.070   -2.102  52.914096  32.038348
    1998  41.039    0.114  55.983070  37.204183
    1999  39.288    0.086  56.563346  34.349302

In [29]:
merged['Debt_year_zscore'] = (merged['Debt']-merged['Mean_debt'])/merged['Std_debt']
merged.head()

            Debt  Surplus  Mean_debt   Std_debt  Debt_year_zscore
ISO Year
ABW 1995  55.088   -0.834  59.230258  39.320475         -0.105346
    1996  54.771   -2.343  54.304031  36.582729          0.012765
    1997  51.070   -2.102  52.914096  32.038348         -0.057559
    1998  41.039    0.114  55.983070  37.204183         -0.401677
    1999  39.288    0.086  56.563346  34.349302         -0.502931

# String Methods &#x1F3BB;
Pandas has a [set of methods](https://pandas.pydata.org/docs/user_guide/text.html) for working with string series element-wise. These are accessed using the syntax,
```python
MySeries.str.SomeStringMethod()
```
Let's see an example of these

In [30]:
MessyStrings = pd.DataFrame({'Name':['aLeJanDrO HeRrEra', 'MiTCHElL vaLdes Bobes'],'Field':['Industrial Organization','Macroeconomics']})
MessyStrings

                    Name                    Field
0      aLeJanDrO HeRrEra  Industrial Organization
1  MiTCHElL vaLdes Bobes           Macroeconomics

In [31]:
TidyStrings = (
    MessyStrings
    .assign(Name = lambda x: x['Name'].str.title()) # Format names
)
print(TidyStrings)

# Or the alternative
print('Alternative:')
TidyStrings = MessyStrings.copy()
TidyStrings['Name'] = TidyStrings['Name'].str.title()
print(TidyStrings)

                    Name                    Field
0      Alejandro Herrera  Industrial Organization
1  Mitchell Valdes Bobes           Macroeconomics
Alternative:
                    Name                    Field
0      Alejandro Herrera  Industrial Organization
1  Mitchell Valdes Bobes           Macroeconomics

We can also split strings on certain characters

In [32]:
FirstLast = TidyStrings['Name'].str.split(' ', n = 1, expand = True).rename(columns={0:'First',1:'Last'})
FirstLast

       First          Last
0  Alejandro       Herrera
1   Mitchell  Valdes Bobes

In [33]:
# We can bring this new variables back into our data
pd.concat([TidyStrings,FirstLast], axis = 1)

                    Name                    Field      First          Last
0      Alejandro Herrera  Industrial Organization  Alejandro       Herrera
1  Mitchell Valdes Bobes           Macroeconomics   Mitchell  Valdes Bobes

There are many other useful string methods. We encourage you to [read up on them](https://pandas.pydata.org/docs/user_guide/text.html).

## 📚 Exercise: Survey of Expected Salaries  

Imagine that got survey data from incoming students. Each row has state, year, name, school email, major, and expected salary. I want to reshape this so each observation is `(state, year, school, major)` with:

- `avg_salary`: average expected salary  
- `n`: number of respondents  

### Tasks
1. Clean the `major` strings (strip spaces, uppercase).  
2. Get the `school` from the email (part after `@`).  
3. Group by `(state, year, school, major)` and compute `avg_salary` and `n`.  
4. Reshape so metrics are stacked (`metric`, `value`).

In [34]:
raw = pd.DataFrame({
    "state": ["CA","CA","CA","CA","NY","NY","WI","WI","WI","TX","TX","TX",
              "FL","FL","IL","IL","MA","MA","WA","WA","CO","CO","NC","NC",
              "GA","GA","MI","MI","OH","OH","AZ","AZ","VA","VA","OR","OR"],
    
    "year":  [2024,2024,2024,2025,2024,2025,2024,2025,2025,2024,2025,2025,
              2024,2025,2024,2025,2024,2025,2024,2025,2024,2025,2024,2025,
              2024,2025,2024,2025,2024,2025,2024,2025,2024,2025,2024,2025],
    
    "name":  ["  alice  wong ","BoB  Diaz","  carla  r.","JÜRGEN MEYER",
              "lena   k.","  juan p ","Luisa   MARTÍN","  diego   r",
              "Sam   T.","Ravi K.","  anita   S.","  george   M ",
              "María José  García","  raj   patel","  li   wei  chen","SARAH O'CONNOR",
              "josé-antonio  ruiz","  anna-marie   dubois","david  mcpherson jr.",
              "  priya   sharma  ","michael  van der berg","  elena  rossi  ",
              "ahmed   al-rashid","  sophie   müller ","  hiroshi   tanaka",
              "  isabella   da silva","  erik   jönsson","  fatima   hassan  ",
              "  aleksandr   petrov","nicole   van   houten","  carlos   mendez jr",
              "  kenji   nakamura","dr.  patricia   white","ms.  jennifer   brown",
              "  prof.  robert   taylor","  mr.   william   davis"],
    
    "email": [
        "alice@illinois.edu","bob@indiana.edu","carla@iowa.edu","jurgen@maryland.edu",
        "lena@msu.edu","juan@minnesota.edu","luisa@nebraska.edu","diego@northwestern.edu",
        "sam@ohio-state.edu","ravi@purdue.edu","anita@rutgers.edu","george@wisc.edu",
        "maria.garcia@illinois.edu","raj.patel@indiana.edu","li.chen@iowa.edu","sarah.oconnor@maryland.edu",
        "jose.ruiz@msu.edu","anna.dubois@minnesota.edu","david.mcpherson@nebraska.edu",
        "priya.sharma@northwestern.edu","michael.berg@ohio-state.edu","elena.rossi@purdue.edu",
        "ahmed.rashid@rutgers.edu","sophie.muller@wisc.edu","hiroshi.tanaka@illinois.edu",
        "bella.silva@indiana.edu","erik.jonsson@iowa.edu","fatima.hassan@maryland.edu",
        "alex.petrov@msu.edu","nicole.houten@minnesota.edu","carlos.mendez@nebraska.edu",
        "kenji.nakamura@northwestern.edu","patricia.white@ohio-state.edu","jennifer.brown@purdue.edu",
        "robert.taylor@rutgers.edu","william.davis@psu.edu"],
    
    "major": [" econ ","Econ"," ECON","cs",
              "Cs "," finance","Finance "," finance  ",
              "cs","econ","econ","finance",
              " business ","Business Admin","comp sci","Computer Science",
              "COMPUTER SCI","mechanical eng","Mech Eng","electrical engineering",
              "psychology","Psych","PSYCHOLOGY"," biology ",
              "Bio","chemistry","Chem","CHEMISTRY",
              "mathematics","Math","physics","Physics",
              "english lit","History"," sociology ","Philosophy"],
    
    "expected_salary": [78000, 65500, 82000, 95000,
                        72000, 88000, 55000, 61000,
                        64000, 70000, 75000, 68000,
                        85000, 58000, 92000, 105000,
                        62000, 89000, 67000, 73000,
                        45000, 48000, 52000, 59000,
                        55000, 71000, 63000, 69000,
                        77000, 74000, 81000, 86000,
                        42000, 51000, 46000, 49000],

})
raw.head()

  state  year            name                email   major  expected_salary
0    CA  2024    alice  wong    alice@illinois.edu   econ             78000
1    CA  2024       BoB  Diaz      bob@indiana.edu    Econ            65500
2    CA  2024       carla  r.       carla@iowa.edu    ECON            82000
3    CA  2025    JÜRGEN MEYER  jurgen@maryland.edu      cs            95000
4    NY  2024       lena   k.         lena@msu.edu     Cs             72000

In [42]:
# 1. Clean the 'major' strings
raw['major'] = raw['major'].str.strip().str.upper()

# 2. Extract 'school' from email (part after '@', before '.')
raw['school'] = raw['email'].str.split('@').str[1].str.split('.').str[0]

# 3. Group by (state, year, school, major) and compute avg_salary and n
grouped = (
    raw
    .groupby(['state', 'year', 'school', 'major'], as_index=False)
    .agg(avg_salary=('expected_salary', 'mean'), n=('expected_salary', 'size'))
)

# 4. Reshape so metrics are stacked (metric, value)
stacked = (
    grouped
    .set_index(['state', 'year', 'school', 'major'])
    .stack()
    .reset_index()
    .rename(columns={'level_4': 'metric', 0: 'value'})
)

stacked.head()

  state  year        school    major      metric    value
0    AZ  2024      nebraska  PHYSICS  avg_salary  81000.0
1    AZ  2024      nebraska  PHYSICS           n      1.0
2    AZ  2025  northwestern  PHYSICS  avg_salary  86000.0
3    AZ  2025  northwestern  PHYSICS           n      1.0
4    CA  2024      illinois     ECON  avg_salary  78000.0


# Have a Great Weekend! &#x1F44B;